### PR TITLE
N36: Agma

### PR DESCRIPTION
**Pull request by TuckerBMorgan**
Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/1098

### CODE REVIEW

**Review by AngelOnFira — CHANGES_REQUESTED** [review]
The gif is quite large, can you reduce it to <2.5MB? Otherwise lgtm :)

**Comment by TuckerBMorgan** [comment]
ok updated!

**Comment by AngelOnFira** [comment]
The file is still showing as 5MB, are you sure you updated it properly?

**Review by ozkriff — APPROVED** [review]
:+1: seems like something went wrong with image optimization so I optimized it myself - hope it's ok

**Comment by ozkriff** [comment]
Thanks for the PR!

**Comment by TuckerBMorgan** [comment]
Yeah that is fine, sorry for the extra work

**Pull request merged**
