### PR TITLE
Simplify lints

### LINKED ISSUE #639: Line Length Lint
Currently, a `line-length` lint is enabled and set to 80 chars. In https://github.com/rust-gamedev/rust-gamedev.github.io/pull/638 @Keavon proposed to get rid of it:

> @Keavon: this be a good place to propose we get rid of the nonsensical linter requirement for a line length limit in markdown files? It's seriously quite a pain and provides no benefit.
> @17cupsofcoffee: I'm not particularly attached to the line length limit (and if we do keep it, it might make sense to bump it up to 120 characters or something like that), but will see what the other maintainers think.
> @Keavon: Since 120 characters is shorter than a paragraph, that wouldn't really be an improvement. Let's stick to proposing no limit.

I don't agree that the current limit is nonsensical - it's an [ancient question](https://about.gitlab.com/blog/2016/10/11/wrapping-text) with no universally right answer that fits for all projects. In my personal experience, lengthy versioned and collectively reviewed/edited Markdown files with no line limit were quite annoying. Also, following to [semantic line wrapping](https://scott.mn/2014/02/21/semantic_linewrapping) seems to ease the downsides of strict line limits a lot.  Lots of similar projects (the official Rust blog, Veloren blog, etc) seem to come to the same conclusion.

So I'd prefer to keep the limit (as it simplifies versioning, reviewing, and collective editing) but if there're a lot of contributors who hate it then it might be worth considering switching it off (or raising the limit to 100 or 120 chars).

What do you think?

### PR DESCRIPTION
**Pull request by janhohenheim**
Fixes #639 
Additionally removes lint for ul list style.

I'm relaxing our lints massively because I want to streamline the process for potential contributors by reducing as much friction as possible. If the current editors since the revival find the lints too relaxed, I'm very open to changing them in the next release cycle.

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
Very much in favour of this - it's the style of the *output* we care about, not so much the Markdown itself. As long as the submission renders nicely and is easily reviewable/editable, I don't think there's much value in chasing people over line lengths or list styles tbh.

**Comment by Keavon** [comment]
I'll just drop a comment to mention that any line length limit (like 160 now) still means contributors can't just type text and will still have to submit a PR, learn that it fails CI, investigate, make changes to break the text across lines, and re-submit the PR at least once more. Doubling the limit makes it slightly less annoying but doesn't fix that frustrating and (for new contributors) surprising limitation. Make of that what you will, but that's just an explanation of my view.

**Comment by janhohenheim** [comment]
@Keavon good point. I decided to leave in a limit as a compromise since #639 shows that editors generally really want a character limit. If I see many contributors running into this, I'll open a PR removing the limit altogether.

**Comment by janhohenheim** [comment]
Got a follow-up at #1480

**Pull request merged**
