### PR TITLE
N23: "thRustEngine" demo

### PR DESCRIPTION
**Pull request by experiment9123**
Newsletter 23 #677

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Please can you reformat this to meet the [style guidelines](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md#style-guidelines)? Primarily:

* There should be one blank line above and below each heading and image (no more or less).
* Lines should be 80 characters long at most.

Also, it looks like you've uploaded a screenshot to the root of the repo - can you delete this?

**Comment by experiment9123** [comment]
yikes ok I deleted the extraneous screenshot. Is it lines or sentances of 80chars? I've shortened and split them etc- is this closer?

**Review by 17cupsofcoffee — APPROVED** [review]
It's 80 per line rather than per sentence (just makes the diffs a bit easier to read). I was able to fix the last few bits myself, thanks for sorting the screenshot issues :)

**Comment by experiment9123** [comment]
awesome, thanks, i'll know for next time

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
