### PR TITLE
N16: add KAS entry

### PR DESCRIPTION
**Pull request by dhardy**
Re #365: add KAS news section.

There isn't a lot to say about this release so part of the entry is waffle copied from N13.

### CODE REVIEW

**Comment by dhardy** [comment]
I need to rebase?

**Comment by 17cupsofcoffee** [comment]
CI job failed due to an internal error, I've done a manual rerun.

**Review by 17cupsofcoffee — APPROVED** [review]
Just Github Actions having a hiccup by the looks of it - your change is fine :)

**Review by ozkriff — APPROVED** [review]
:+1: (added an image and swapped the paragraphs' order)

**Comment by ozkriff** [comment]
Thanks!

**Pull request merged**
