### PR TITLE
N14: Way of Rhea Cleanup

### PR DESCRIPTION
**Pull request by MasonRemaley**
Replaces the large images with thumbnail links! #278

### CODE REVIEW

**Comment by ozkriff** [comment]
Works fine in GitHub preview, but our Zola theme doesn't seem to be work with multiple images per line:

image

**Comment by ozkriff** [comment]
What about combining the images into one? Something like

image

?

**Comment by MasonRemaley** [comment]
Ah gotcha, good idea--just did that!

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Merged, thanks!

**Pull request merged**
