### PR TITLE
N14: add rg3d and rusty-editor

### PR DESCRIPTION
**Pull request by mrDIMAS**
_Part of #278 ("Newsletter 14")_

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
The content looks good! I don't think there's a ton of value in having the `### [rg3d][rg3d] and [rusty-editor][rusty editor]` heading, though. Could you remove that and make the two other headings a level higher?

**Review by 17cupsofcoffee — APPROVED** [review]
Thank you for making the changes, approving :)

**Comment by ozkriff** [comment]
@mrDIMAS :thinking: It'd be cool to add an image or a gif to the rg3d section. My first thought is to convert https://twitter.com/DmitryS36934349/status/1239923629883875328 into a gif

**Review by ozkriff — APPROVED** [review]
:+1: (optimized images a bit, made a few style tweaks for consistency)

**Comment by ozkriff** [comment]
Merged, thanks for the PR! :-D

**Pull request merged**
