### PR TITLE
N33: Oasis of Lost Hope

### PR DESCRIPTION
**Pull request by Bromeon**
_Part of #1010_

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]
:+1: though i'd be good to reduce the image size

**Comment by Bromeon** [comment]
>  though i'd be good to reduce the image size

Do you know any good tool for this? I already shrunk it from 1.4MB 😬

**Comment by ozkriff** [comment]
I'd convert it from png to jpg

**Comment by Bromeon** [comment]
Changed to .jpg, halved the size. I was first worried it would lose quality, but seems OK with this quantization.

**Comment by 17cupsofcoffee** [comment]
For future reference, I usually use https://tinypng.com if I need to shrink a PNG without substantial quality loss :)

**Pull request merged**
