### PR TITLE
N42: Release

### PR DESCRIPTION
**Pull request by AngelOnFira**
_Part of #1267_

Hoping to get this released soon!

To review, open the [live site](https://agitated-saha-af60ca.netlify.app/news/042/) (6289fbb), and try and find anything that looks out of place. Leave a comment about it here, and I'll get it fixed!

### CODE REVIEW

**Review by 17cupsofcoffee — COMMENTED** [review]
Looks good, just a few minor issues I spotted:

* The link to the meetup recording points at the wrong video (it's the August 2022 one).
* Idu's main link and screenshot are broken.

**Comment by janhohenheim** [comment]
Hope I may sneak in https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1285 before the release 😉

**Review by sanbox-irl — COMMENTED** [review]
The Idu section looks a little broken, otherwise looks good to me

**Review by ozkriff — APPROVED** [review]
LGTM, except for a couple of the above-mentioned issues

**Comment by ozkriff** [comment]
Forest is still busy so I'll release the thing

**Pull request merged**
