### PR TITLE
N16: Dotrix

### PR DESCRIPTION
**Pull request by Lowentwickler**
#365

### CODE REVIEW

**Review by kvark — APPROVED** [review]
Would you want to link to Dotrix Weekly reports that happened?

**Comment by Lowentwickler** [comment]
@kvark yes, why not

**Review by ozkriff — APPROVED** [review]
:thumbsup:

**Comment by ozkriff** [comment]
Merged manually in https://github.com/rust-gamedev/rust-gamedev.github.io/commit/1a9f94736401f4f401ace10984003f40c8798fb4 , thanks!

**Pull request closed without merging**
