### PR TITLE
Check for dead links

### LINKED ISSUE #189: CI: Add deadlink checks
Related to #30 (_"CI: Add markdownlint check"_)

### PR DESCRIPTION
**Pull request by janhohenheim**
Fixes #189

### CODE REVIEW

**Comment by 17cupsofcoffee** [comment]
FYI, Zola has a broken link checker built-in (though it's not super well-documented) - might be worth seeing how well that stacks up against this external one? That would allow it to work on local builds/without extra automation.

If that's not a good fit, this sounds like a decent alternative, though :smile:

**Comment by janhohenheim** [comment]
@17cupsofcoffee thanks! I intentionally am not using that because I only want to lint the files touched by the current PR, as no one should have to go over our old newsletters when links break. I don't think Zola supports that, does it?

**Comment by janhohenheim** [comment]
Done 🎉

**Comment by 17cupsofcoffee** [comment]
> @17cupsofcoffee thanks! I intentionally am not using that because I only want to lint the files touched by the current PR, as no one should have to go over our old newsletters when links break. I don't think Zola supports that, does it?

That makes sense :+1: And no, I don't think Zola supports that.

**Comment by janhohenheim** [comment]
@17cupsofcoffee I fixed some issues and squashed all of my changes into one clean commit. Could you approve the PR? :)

**Review by mamaicode — APPROVED** [review]

**Pull request merged**
