### PR TITLE
N17: Cheese

### PR DESCRIPTION
**Pull request by expenses**
Part of #408.

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
The content looks good, just one formatting issue being flagged up by the CI build: 

```
content/posts/newsletter-017/index.md:96 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- [wgpu-rs] for rendering,"]
```

Adding a line break before the list should fix it.

**Review by 17cupsofcoffee — APPROVED** [review]
:+1: LGTM

**Review by ozkriff — APPROVED** [review]
:rocket:

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
