### PR TITLE
rafx and basis-universal

### PR DESCRIPTION
**Pull request by aclysma**
This is a draft, still need a few tweaks and double-check the links.

Should rafx be considered a library/tooling update or an engine? It probably sits somewhere between something like wgpu and bevy/amethyst.

### CODE REVIEW

**Comment by kvark** [comment]
This is super exciting!
Note that you'll likely exceed this limit here:
> All the (rendered) text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).

**Comment by kvark** [comment]
I guess you could also do the trick I have with gfx/wgpu/naga and just split it into multiple independent sections, one for rafx, another for rafx-assets, another for rafx-framework :)

**Comment by aclysma** [comment]
Rafx is still around ~1150 characters (down from about 1900). Shortening it may require leaving out references to distill or the other PDFs that I'd prefer to cite/credit. How strict is the character limit?

**Review by 17cupsofcoffee — APPROVED** [review]
Don't know about the other maintainers, but I think this is okay? The diff is fairly long cause of the links but the actual rendered sections don't seem too chunky now, given it's (as far as I know?) the first mention of these projects in the newsletter.

**Pull request merged**
