### PR TITLE
N15: Proton 5.13-1

### PR DESCRIPTION
**Pull request by PatrickHoward**
This is a PR for the section on Proton for Newsletter 15 (#320):

### [Proton][Proton-Github] 5.13-1
In addition to adding Linux Support for more Windows-exclusive games, 
Valve Software's wine-based translation layer for Linux: Proton now 
includes Rust as part of its build system. 
[Media Converter][Proton-Media-Converter-Github], is a Proton module 
written in Rust as a gstreamer plugin to convert certain media encodings 
from one format to another.

Doucmentation for building Proton is available on [Github][Proton-Github]. 
Further documentation on Media Converter and its source code is available
on the module's [repository][Proton-Media-Converter-Github]

[Proton-Github]: https://github.com/ValveSoftware/Proton
[Proton-Media-Converter-Github]: https://github.com/ValveSoftware/Proton/tree/proton_5.13/media-converter

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
The content looks good! There's just a few style errors on the CI check:

```
content/posts/newsletter-015/index.md:169 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### [Proton][Proton-Github] 5.13-1"]
content/posts/newsletter-015/index.md:170:70 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-015/index.md:171:68 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-015/index.md:172:43 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-015/index.md:173:69 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-015/index.md:174:73 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-015/index.md:177:75 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
```

**Comment by PatrickHoward** [comment]
Ope, thanks for pointing that out. I just made some changes that should make the linter happy now.

**Review by 17cupsofcoffee — APPROVED** [review]
:+1: perfect

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Thanks!

**Pull request merged**
