### PR TITLE
Script to help preparing new newswletters

### PR DESCRIPTION
**Pull request by Vrixyz**
Hey, I'd like to help, this script is pretty basic but would that help in onboarding new editors ? by simplifying technical burden and "document by code" the process ?

### CODE REVIEW

**Comment by AngelOnFira** [comment]
Ideally, I think this should be set up in a GitHub Action that creates the file, and creates the issue as well. I'd opt for it to be created on the 28th of the month, that way it's at least a few days before the beginning of the next month. We can probably start with this as a base though :)

**Comment by Vrixyz** [comment]
I'm trying on my repository : https://github.com/Vrixyz/rust-gamedev.github.io/blob/source/.github/workflows/prepare_newsletter.yml ; ci are always a pain to configure though.

**Comment by janhohenheim** [comment]
Created a fully automated alternative: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1464

**Comment by Vrixyz** [comment]
https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1464 seems great but can be seen as complementary to this pull request:
- [This PR (#1457)](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1457) prepares the new file (blog entry as a draft)
- [#1464](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1464) prepares a new issue

**Comment by janhohenheim** [comment]
@Vrixyz oh, I didn't realize that your script also prepared the post itself, that's pretty cool!

Wouldn't it be easier to have this as a GH Action as well? Remember you can also manually trigger those.

**Comment by janhohenheim** [comment]
Added the newsletter generation as well now :)

**Pull request closed without merging**
