### PR TITLE
Newsletter 13: Chillscapes

### PR DESCRIPTION
**Pull request by ecton**
Part of #232 

One of my links is longer than the softwrap limit, let me know if that's an issue! Thank you for letting me contribute!

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Your content looks good, but some of the links are broken - to use the footnote-style links, the ID needs to be in square brackets, not parentheses. e.g. `[Kludgine](kludgine)` should be `[Kludgine][kludgine]`.

You use parentheses when you're placing the URL inline - so for example, `[Chillscapes](https://khonsulabs.itch.io/chillscapes)` is fine and will work :)

The link going past the line length limit is fine, there's no way to break that over multiple lines and it's not tripping up the lint CI job.

**Comment by ecton** [comment]
Sorry about that, first time I used the footnote link syntax, and I didn't notice the nuance. Of course, I also didn't test all of the links in the preview.... and more importantly the one I tested was the one that wasn't converted lol

All the links should be fixed and working now. Thank you!

**Review by 17cupsofcoffee — APPROVED** [review]
:+1: All looks good now!

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
