### PR TITLE
N43: CyberGate

### PR DESCRIPTION
**Pull request by cybersoulK**
Part of #1287

### CODE REVIEW

**Comment by cybersoulK** [comment]
i tried to compress video footage several times, but the smallest was 2.6 mb mp4. Attempted to convert mp4 to gif and compress it, but the resolution becomes 10 times worse.
I can provide with an image or a video link to youtube if preferred. thank you

**Review by ozkriff — APPROVED** [review]
Yeah, sorry, we only use static images or gif. But I've played around with ezgif.com and got a semi-ok gif from it. Hope you're ok with this quality.

**Comment by ozkriff** [comment]
Thanks for the PR! And feel free to ping me if you want to change something about the gif.

**Comment by cybersoulK** [comment]
Thank you very much! looks good enough for me

**Pull request merged**
