### PR TITLE
N19: Add wgpu/gfx/naga news

### PR DESCRIPTION
**Pull request by kvark**
_Part of #496_

### CODE REVIEW

**Review by ozkriff — CHANGES_REQUESTED** [review]
> All the (rendered) text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).

it's 1658 atm. The content needs to be either shortened or split into more sections.

> No bold/italic/etc formatting - only links and one plain list without nesting per section.

There's a nested list atm

**Comment by kvark** [comment]
Thank you for the review! How about now?

**Comment by ozkriff** [comment]
wgpu and gfx sections look great but naga's nested list still doesn't fit the new simplified guidelines

**Comment by kvark** [comment]
Removed the nesting now. I find this limitation unfortunate :/

**Review by 17cupsofcoffee — APPROVED** [review]
LGTM now :+1:

Personally I think one level of nesting wouldn't be the worst thing in the world, if a list needed breaking up into categories or something like that.

I think the intent of the guidelines is to nudge people away from just dumping a massive changelog in each newsletter (writeups are a bit nicer to read), but for big projects with lots of seperate work streams like WGPU, I feel like it'd be hard to avoid the bullet point approach. Might be one to discuss going forward.

**Comment by kvark** [comment]
I admit this PR does look rather boring with these lists and no screenshots. But that's what we have right now, so better than nothing anyway.

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

And, yeah, maybe we should relax some of these formatting limitations. :thinking:

**Pull request merged**
