### PR TITLE
N19: senior_sky

### PR DESCRIPTION
**Pull request by pmathia0**
Part of #496

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]
lgtm except for two lists. though, the second list feels ok here.

@17cupsofcoffee @AngelOnFira wdyt?

**Comment by pmathia0** [comment]
Thanks. I can remove the bullet about those two, didn't mean thay badly

**Review by 17cupsofcoffee — APPROVED** [review]
Looks okay IMO - two lists is fine if they're both short, the only kind I have a problem with is when people try to dump their entire changelog in the newsletter :p

**Comment by ozkriff** [comment]
Ok, merged! :)

Thanks for the PR!

**Comment by pmathia0** [comment]
> Looks okay IMO - two lists is fine if they're both short, the only kind I have a problem with is when people try to dump their entire changelog in the newsletter :p

Will try to avoid that next time :)

**Pull request merged**
