### PR TITLE
N17: Kira

### PR DESCRIPTION
**Pull request by tesselode**

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Content looks good, just one linter issue:
```
content/posts/newsletter-017/index.md:99 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- Arrangements for stitching t..."]
```

**Comment by tesselode** [comment]
my bad, i didn't have the linter turned on

**Review by 17cupsofcoffee — APPROVED** [review]

**Review by ozkriff — APPROVED** [review]
:+1:

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
