### PR TITLE
N20: oxygengine and raui

### PR DESCRIPTION
**Pull request by PsichiX**
_Part of #531_

### CODE REVIEW

**Review by ozkriff — COMMENTED** [review]
There're a few fmt warnings but the content lgtm overall

**Comment by PsichiX** [comment]
ok, gonna look at the logs and fix it right now :)

**Comment by PsichiX** [comment]
warnings are fixed now and linter is green :D

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
