### PR TITLE
N42: torchbearer

### PR DESCRIPTION
**Pull request by redwarp**
Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/1267

### CODE REVIEW

**Comment by redwarp** [comment]
Oops, my vscode plugin updated the whole markdown file, let me revert that first

**Comment by redwarp** [comment]
Okay that is better, ready for review

**Review by ozkriff — APPROVED** [review]
:+1:

**Comment by ozkriff** [comment]
Merged, thanks!

**Pull request merged**
