### PR TITLE
N18: Harvest Hero

### PR DESCRIPTION
**Pull request by Bombfuse**
_Part of #455_

### CODE REVIEW

**Comment by ozkriff** [comment]
:construction:

**Comment by Bombfuse** [comment]
Is there something missing? I'm unsure what 🚧 means

**Review by ozkriff — APPROVED** [review]
:+1: (optimized the image and made a few small style & fmt tweaks for consistency with the rest of the newsletter).

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
