### PR TITLE
Newsletter 7: Assorted libraries and tools

### PR DESCRIPTION
**Pull request by AngelOnFira**
Part of #64 ("Newsletter 7: Coordination/Tracking #64")

This will include:
- shipyard
- crow 0.3
- patchwork
- KAS
- image v0.23

This is a WIP as I might not do anymore tonight, and if I don't finish the others before it needs to be posted, then someone else can take the flag. I'll update here as I work on other sections.

### CODE REVIEW

**Comment by 17cupsofcoffee** [comment]
(Oh whoops, jumped the gun on approving, didn't notice you wanted to add more - take that as an approval for what you've done so far :p)

**Comment by ozkriff** [comment]
@AngelOnFira how is it going?

**Comment by ozkriff** [comment]
@AngelOnFira have you seen [this comment](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/79#issuecomment-594322188) by @PsichiX?

> the reason i wanted to add something to the Oxygengine part is that i wanted to add important node about the Visual Novel and Animation modules (this note is published in rust gamedev subreddit with short movie clip: https://www.reddit.com/r/rust_gamedev/comments/fd7kza/oxygengine_visual_novel_and_animation_modules_are/?utm_source=share&utm_medium=web2x), i could add that to @AngelOnFira MR, but if you think that it is not possible, i'm not gonna block this PR :)

If these updates describe what has been done during February, I'm ok with including them.

**Comment by AngelOnFira** [comment]
Ok @ozkriff this should be good to go! Tell me if anything needs changing. @PsichiX I'm leaving OXY to you, not sure if that update made it your way.

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
