### PR TITLE
add entry for bevy_rapier_collider_gen library in 040

### PR DESCRIPTION
**Pull request by shnewto**
_Part of #1203_

👋 hello! if there's still a chance to squeak in to newsletter 40 I'd love to! I just released (yesterday) a library for generating colliders in bevy. Thanks for your time!

### CODE REVIEW

**Comment by ozkriff** [comment]
@shnewto November's issue is supposed to cover events from November - I'm just really late with releasing it. :sweat: 

Judging by the repo's history, all the work on bevy_rapier_collider_gen happened during Dec - are you ok if we include it in the next newsletter issue then?

**Comment by shnewto** [comment]
@ozkriff ah that makes complete sense! i'm definitely okay with it moving to the next newsletter. thank you!!

**Comment by ozkriff** [comment]
Great, added to the draft of the next issue's plan https://hackmd.io/@gamedev-rs/n41

**Comment by shnewto** [comment]
awesome, thanks!!

**Pull request closed without merging**
