### PR TITLE
N15: Release

### PR DESCRIPTION
**Pull request by ozkriff**
Preview (https://github.com/rust-gamedev/rust-gamedev.github.io/commit/2a0df9163c0c0492e01061c2a74e5a7ef2665ad8): https://rust-gamedev-preview.netlify.app/posts/newsletter-015

Everyone is invited to review!

:timer_clock: Hope to merge this today +- at 15:00 UTC (in ~8 hours from now) if there're no objections.

_Part of #320 ("Newsletter 15")_

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
LGTM 👍

**Review by repi — APPROVED** [review]
Looks good!

Small Rust GPU section tweak that we would like to get in #362

**Comment by casperstorm** [comment]
LGTM.

**Review by Wodann — APPROVED** [review]

**Comment by Wodann** [comment]
Nice work everyone! ❤️

**Comment by AngelOnFira** [comment]
I ran through and found some Oxford commas that we're needed, changes shouldn't be too intrusive #363

**Review by kvark — APPROVED** [review]

**Comment by tuzz** [comment]
Looks good. :shipit:

**Pull request merged**
