### PR TITLE
N24: Zemeroth, Flesh and Macroquad

### PR DESCRIPTION
**Pull request by 17cupsofcoffee**
_Part of #719_

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]
Thanks! Sorry that I'm not able to actively participate this month.

**Comment by ozkriff** [comment]
@not-fl3 fyi

**Comment by 17cupsofcoffee** [comment]
@ozkriff: It's no problem, that's why we have three editors :p

**Comment by not-fl3** [comment]
Great job, thank you! If you don't mind - I added a little sub-section for macroquad update (but if it is too late - no worries!)

https://github.com/rust-gamedev/rust-gamedev.github.io/pull/746

**Pull request merged**
