### PR TITLE
N28: Rustaction Station 48

### PR DESCRIPTION
**Pull request by AngelOnFira**
Part of #852

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]
lgtm, but maybe it's worth adding an image?
https://rustacean-station.org/images/artwork.jpg

**Comment by AngelOnFira** [comment]
@ozkriff I tried this, but since it's a square, it took up a ton of space. Do we have a way to specify size that an image should render as?

**Comment by AngelOnFira** [comment]
image

**Comment by ozkriff** [comment]
> Do we have a way to specify size that an image should render as?

nope, but I guess we can manually frame the image a bit?

image

**Review by ozkriff — APPROVED** [review]

**Pull request merged**
