### PR TITLE
N20: Bevy Retro

### PR DESCRIPTION
**Pull request by zicklag**
For #531.

### CODE REVIEW

**Comment by jamadazi** [comment]
I think that the notice about Katharos License should be more prominent/visible. The small link at the end feels too hidden. It is an unusual license and it should be made clear to potential users of the software.

**Comment by zicklag** [comment]
I moved the link to the second paragraph which should be clear enough.

The [Katharos License README](https://github.com/katharostech/katharos-license#open-questions) also has an Open Questions section to make it clear that there were concerns brought up about the license and to point to that discussion.

**Comment by AngelOnFira** [comment]
Hey @zicklag, due to the ethical/moral/religious implications behind the Katharos License, we're going to ask that you make your license sections in the newsletter a lot more explicit about its nature. If you could change the sections out to what is included below, then we should be ok to merge it into the newsletter:

```
This project was released under the [Katharos License][katharos_license]. This license has moral and ethical implications that you may or may not agree with, so please read it before making use of this project.
```

**Comment by zicklag** [comment]
Pushed an update: +1:

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
