### PR TITLE
N37: Notan v0.6

### PR DESCRIPTION
**Pull request by Nazariglez**
Part of #1134 

Thanks!

### CODE REVIEW

**Review by ozkriff — CHANGES_REQUESTED** [review]
Could you please make the gif smaller? <2.5mb

**Comment by Nazariglez** [comment]
Of course! Done

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
It looks like the GIF was put in the `035` folder instead of overwriting the old version?

**Comment by Nazariglez** [comment]
Oops! Sorry about this, I did it in a rush and I did not check it twice. Fixed.

**Review by ozkriff — APPROVED** [review]
:+1:

**Review by 17cupsofcoffee — APPROVED** [review]

**Pull request merged**
