### PR TITLE
N36: Way of Rhea

### PR DESCRIPTION
**Pull request by MasonRemaley**
Let me know if you need any tweaks! :)

_Part of #1098_

### CODE REVIEW

**Review by AngelOnFira — APPROVED** [review]
It's been quite a busy month :smile:

**Review by ozkriff — APPROVED** [review]
:rocket:

**Comment by ozkriff** [comment]
Thanks!

**Comment by MasonRemaley** [comment]
> It's been quite a busy month 😄

It has 😅

**Pull request merged**
