### PR TITLE
N17: starframe

### PR DESCRIPTION
**Pull request by MoleTrooper**
Part of #408

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]

**Review by ozkriff — CHANGES_REQUESTED** [review]
The text itself LGTM, though the GIF is too large. In general, we try to keep GIFs under 2MBs. Could you optimize it a little bit?

> GIFs should be <2MB in size (ezgif.com is a nice online tool for quick editing/optimization)

**Comment by MoleTrooper** [comment]
Sorry, I didn't read the contributing guide thoroughly enough. I couldn't get it under 2MB using ezgif's optimizer so I cut the length instead, should be good now

**Review by ozkriff — APPROVED** [review]
:+1:

**Comment by ozkriff** [comment]
Thanks, merged!

**Pull request merged**
