### PR TITLE
N17: add Bezier

### PR DESCRIPTION
**Pull request by pum-purum-pum-pum**
Part of #408

### CODE REVIEW

**Review by 17cupsofcoffee — COMMENTED** [review]
I think this should be in the Learning Material Updates section, rather than Game Updates?

**Comment by pum-purum-pum-pum** [comment]
sure, thank you!

**Review by ozkriff — APPROVED** [review]
:+1: (nade a few fmt tweaks)

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
