### PR TITLE
N52: Way of Rhea

### PR DESCRIPTION
**Pull request by MasonRemaley**
Let me know if anything should be changed! :)

_Part of #1523_

### CODE REVIEW

**Comment by janhohenheim** [comment]
The post looks good in general, but some readers gave us feedback about the games section sometimes reading more like an advertisement rather than something targeted at other devs. Is there some kind of devlog that we can include? Some interesting technical aspect to highlight? 
I do want to include updates to your game, as I want to highlight games made in Rust, but given the reader feedback, I'd trim the entry in its current form if that is alright with you.

**Review by janhohenheim — CHANGES_REQUESTED** [review]
The post looks good in general, but some readers gave us feedback about the games section sometimes reading more like an advertisement rather than something targeted at other devs. Is there some kind of devlog that we can include? Some interesting technical aspect to highlight? Your [post about the AMA](https://gamesbymason.com/2024/06/01/wor-ama/) is probably also worth including.
I do want to include updates to your game of course, but given the reader feedback I'd trim the entry in its current form if that is alright with you.

BTW, congrats on having so many positive Steam reviews! People really seem to like the game ❤️

**Comment by MasonRemaley** [comment]
Ah sorry for the late response! It was my birthday this weekend and I missed this email notification. :)

> The post looks good in general, but some readers gave us feedback about the games section sometimes reading more like an advertisement rather than something targeted at other devs. Is there some kind of devlog that we can include? Some interesting technical aspect to highlight? Your [post about the AMA](https://gamesbymason.com/2024/06/01/wor-ama/) is probably also worth including.

Sure that sounds reasonable! Good call about the AMA post, I totally forgot that that was after the last TMIRGD.

> BTW, congrats on having so many positive Steam reviews! People really seem to like the game ❤️

Thank you!! :)

> I went ahead and commit a [counteroffer](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1531/commits/4d5028145d3801118ca35b593a826868165a5dc3). Is the post alright like this? :)

Thanks for putting together this edit for me--this looks great! I arbitrarily felt like I needed to include updates to the game for some reason, removing those and replacing them with the AMA and stuff was a good call IMO.

**Comment by janhohenheim** [comment]
Great :D Merging

**Review by janhohenheim — APPROVED** [review]

**Pull request merged**
