### PR TITLE
N23: glutin and winit

### PR DESCRIPTION
**Pull request by maroider**
I've mashed out some prose outlining the things I thought were important, as well as some things that aren't quite that important., and I've also included some text about winit since it wasn't included in the last newsletter.

I'll probably write about our need for helping hands tomorrow, and that'll probably require me to cut down the text some more to stay within the length guidelines.

*Part of #677*

### CODE REVIEW

**Comment by maroider** [comment]
I've now added most of the things I wanted to include, bar a link to winit's "good first issues".
The text is unfortunately a bit long, but I'm not sure how to make it shorter.

**Review by ozkriff — APPROVED** [review]
:+1: (Converted to 3rd person)

**Comment by ozkriff** [comment]
@17cupsofcoffee @AngelOnFira i guess the section's size isn't that bad in this case. i'd merge it if there're no objections

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
