### PR TITLE
Release 49

### PR DESCRIPTION
**Pull request by AngelOnFira**
_Part of #1440_

Live site [aac1a94](https://agitated-saha-af60ca.netlify.app/news/049/)

### CODE REVIEW

**Comment by AngelOnFira** [comment]
Hoping for this to go out tomorrow :)

**Comment by ozkriff** [comment]
@AngelOnFira https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1460

**Comment by Braymatter** [comment]
Just a heads up, y'all don't have to include this if you don't want to, but our couch co-op game Roids is written in Bevy and we had our announcement last month w/trailer - we'd definitely appreciate it!

https://playroids.com

**Review by mamaicode — APPROVED** [review]

**Comment by mamaicode** [comment]
All seems fine, my only question is, from now on we will continue fresh or the next release will be from september?
@AngelOnFira @ozkriff

**Comment by janhohenheim** [comment]
Is it fine if I just merge this so it's out of the way? @AngelOnFira @AngelOnFira

**Comment by janhohenheim** [comment]
Little update: Will try to get this out this weekend with a little text saying "Hey, this is late, we know, we did some restructuring in the meantime"

**Review by janhohenheim — APPROVED** [review]

**Comment by janhohenheim** [comment]
The links are understandably outdated; not much we can do about that.

**Pull request merged**
