### PR TITLE
N15: Wilds

### PR DESCRIPTION
**Pull request by zakarumych**
_Part of #320 ("Newsletter 15")_

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
The content looks good :+1: Just needs some style fixes to pass the CI check:

```
content/posts/newsletter-015/index.md:345:81 MD013/line-length Line length [Expected: 80; Actual: 115]
content/posts/newsletter-015/index.md:347:81 MD013/line-length Line length [Expected: 80; Actual: 107]
content/posts/newsletter-015/index.md:348:81 MD013/line-length Line length [Expected: 80; Actual: 95]
content/posts/newsletter-015/index.md:355:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-015/index.md:355:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
content/posts/newsletter-015/index.md:355 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "* [~~Shave more yaks~~]"]
content/posts/newsletter-015/index.md:356:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-015/index.md:356:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
content/posts/newsletter-015/index.md:357:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-015/index.md:357:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
content/posts/newsletter-015/index.md:358:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-015/index.md:358:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
content/posts/newsletter-015/index.md:359:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-015/index.md:359:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
content/posts/newsletter-015/index.md:360:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-015/index.md:360:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
content/posts/newsletter-015/index.md:361:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-015/index.md:361:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
content/posts/newsletter-015/index.md:362:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-015/index.md:362:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
content/posts/newsletter-015/index.md:363:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-015/index.md:363:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
```

**Comment by ozkriff** [comment]
:construction: wip :construction:

**Review by ozkriff — CHANGES_REQUESTED** [review]
@zakarumych Could you shorten the future plans list, please?

**Review by 17cupsofcoffee — APPROVED** [review]
Formatting looks good now, so approving to unblock the merge (subject to ozkriff's stuff being resolved).

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Thanks, merged!

**Pull request merged**
