### PR TITLE
N22: Rustcraft

### PR DESCRIPTION
**Pull request by dskart**
Part of #640

### CODE REVIEW

**Review by ozkriff — COMMENTED** [review]
The description is quite minimal. Maybe add a few overview/context sentences from the readme or the reddit post?

**Review by 17cupsofcoffee — APPROVED** [review]
:+1:

**Comment by 17cupsofcoffee** [comment]
Whoops, didn't notice that trailing space - still getting used to having to manually run CI for new contributors...

**Comment by AngelOnFira** [comment]
:100:

**Pull request merged**
