### PR TITLE
N50: sm64jsarchive (fixed)

### PR DESCRIPTION
**Pull request by uuphoria2**
Part of #1473

### CODE REVIEW

**Review by uuphoria2 — COMMENTED** [review]
also yes this is from in game of sm64jsarchive with the working mmo servers lol

**Comment by janhohenheim** [comment]
Thanks for the contribution! Two points!
- The style checks are failing, but it seems easy to fix:
image
- This seems to be a JS project. Could you elaborate on what this has to do with Rust?

**Comment by uuphoria2** [comment]
> Thanks for the contribution! Two points!
> 
>     * The style checks are failing, but it seems easy to fix:
>       image
> 
>     * This seems to be a JS project. Could you elaborate on what this has to do with Rust?

The backend is in rust also your check failed on the image part of it (sm64jsarchive.png) https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1477/commits/9b4622637360b72d9eed9f22cf7fc7e0e190216d

**Comment by uuphoria2** [comment]
@janhohenheim I tried fixing it please check again also I allowed edits by maintainers just incase.

**Comment by janhohenheim** [comment]
Aah I see. Cool project!

**Comment by janhohenheim** [comment]
@uuphoria2 I can fix the lints myself later if you are otherwise finished with the PR :)

**Comment by uuphoria2** [comment]
> @uuphoria2 I can fix the lints myself later if you are otherwise finished with the PR :)

That would be great if you can

**Comment by uuphoria2** [comment]
> @uuphoria2 I can fix the lints myself later if you are otherwise finished with the PR :)

Im running the rust servers for sm64jsarchive right now so note I might not be as active

**Comment by uuphoria2** [comment]
> > @uuphoria2 I can fix the lints myself later if you are otherwise finished with the PR :)
Please do so, as I dont have much time to work on this pull request cuz im the only one maintaining the rust servers within docker for sm64jsarchive.

**Comment by janhohenheim** [comment]
@uuphoria2 will do, just need some time myself. The newsletter will be sent out on the the 3rd of May, so there's no rush :)

**Review by janhohenheim — APPROVED** [review]
Done now; thanks again for your submission!

**Comment by uuphoria2** [comment]
> Done now; thanks again for your submission!

Thank you so much.

**Comment by uuphoria2** [comment]
I'll just note this to anybody viewing: The stress test already ended on april 10th tho im just here to tell how many people went on it: About 4-3 people and it was still really fun! :D

**Comment by janhohenheim** [comment]
Thanks for the update, I'll make sure to update the info once the editorial period starts :)

**Pull request merged**
