### PR TITLE
N17: 15-minute Santa

### PR DESCRIPTION
**Pull request by dabreegster**
I'll leave out A/B Street updates from this issue; there was lots of work started in December that should be further along next month.

Thanks for organizing this newsletter, as always!

_Part of #408 ("Newsletter 17")_

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Content looks good, just needs a few formatting tweaks to pass CI:
```
content/posts/newsletter-017/index.md:92:81 MD013/line-length Line length [Expected: 80; Actual: 383]
content/posts/newsletter-017/index.md:94:81 MD013/line-length Line length [Expected: 80; Actual: 491]
content/posts/newsletter-017/index.md:96:81 MD013/line-length Line length [Expected: 80; Actual: 115]
```

**Comment by dabreegster** [comment]
Woops, I always forget formatting -- should be fixed, CI is rerunning.

**Review by 17cupsofcoffee — APPROVED** [review]
:+1: Looks good, thanks for the quick fix!

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
