### PR TITLE
fix spelling

### PR DESCRIPTION
**Pull request by Tarnadas**

### CODE REVIEW

**Review by Cooliokid956 — APPROVED** [review]
Karts is correct 👍

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Thanks!

**Comment by Cooliokid956** [comment]
great

**Comment by Cooliokid956** [comment]
also, i had made a pr to fix certain errors and sm64js' spelling, can other people contribute to the newsletter besides those assigned?

**Comment by ozkriff** [comment]
> can other people contribute to the newsletter besides those assigned?

@Cooliokid956 sure, though a PR must be sent to the main repo - https://github.com/rust-gamedev/rust-gamedev.github.io

**Comment by Tarnadas** [comment]
You can change the target of your PR to this repo. I also wanted to say that I’m ok with the changes

**Pull request merged**
