### PR TITLE
Newsletter 13

### PR DESCRIPTION
**Pull request by ozkriff**
Preview (https://github.com/rust-gamedev/rust-gamedev.github.io/commit/b6d0c81753dab747dacd4e4d7b8b1199062c8885): https://rust-gamedev-preview.netlify.app/posts/newsletter-013

Everyone is invited to review!

:timer_clock: Hope to merge this today in a few hours if there're no objections.

_Part of #232 ("Newsletter 13")_

### CODE REVIEW

**Review by kvark — APPROVED** [review]
Thank you for all the work coordinating this!

**Comment by AngelOnFira** [comment]
It might be worth hoisting Bevy to the top of the tooling section, it's quite big news for this month.

**Review by repi — APPROVED** [review]
Nice work and tons of content!

**Review by erlend-sh — APPROVED** [review]

**Comment by ozkriff** [comment]
@AngelOnFira it's a big event but it was decided to sort libs&tools sections from low-level to high-level, so I'm not sure.

**Comment by AngelOnFira** [comment]
Lgtm then :ok_hand:

**Pull request merged**
