### PR TITLE
N14: Way of Rhea

### PR DESCRIPTION
**Pull request by MasonRemaley**
Let me know if the images need to be resized! :)

#278

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
LGTM :+1:

**Review by ozkriff — APPROVED** [review]
:+1: (optimized one of the images & made a few style tweaks for consistency)

**Comment by ozkriff** [comment]
Merged!

**Comment by MasonRemaley** [comment]
Thanks!! 👍 

I'm about to teach a class, but after it's over I can make a PR that makes the images smaller and places them side by side or something--when are you planning on posting the newsletter?

**Pull request merged**
