### PR TITLE
N27: bevy_pen_tool

### PR DESCRIPTION
**Pull request by eliotbo**
_Part of #TODO_

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Content looks good, but could you please include the GIF in your PR, rather than linking to an external one? Lowers the risk of broken links in the future :)

There are also a few minor style issues getting flagged by CI:
```
content/news/027/index.md:276:45 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/news/027/index.md:278:66 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/news/027/index.md:283:69 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/news/027/index.md:284:62 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/news/027/index.md:287 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

**Comment by eliotbo** [comment]
Is it possible to include the GIF locally without forking the whole repo?

**Comment by 17cupsofcoffee** [comment]
Ah, actually, I just noticed the GIF is a little over 2mb (which is usually our max) - could you switch it out for this slightly optimized version?

bevy_pen_tool2

Sorry for the hassle!

**Comment by eliotbo** [comment]
I'd be happy to, but the CONTRIBUTING.md file says "Only include one image (<300kb) or GIF (<2.5mb). ", and the gif is 2.48 mb. Should I still lower its size?

**Comment by 17cupsofcoffee** [comment]
Oh, sorry about that, I misremembered! No problem then, you can leave it as it is.

In the long run, we'd like to convert all submitted GIFs to MP4 (or something like that), but we've not quite found a good workflow for that yet, so trying to balance size vs quality :)

**Review by 17cupsofcoffee — APPROVED** [review]

**Comment by 17cupsofcoffee** [comment]
Looks good now! Will give it a little longer in case either of the other editors want to take a look, then will merge.

**Review by ozkriff — APPROVED** [review]

**Pull request merged**
