### PR TITLE
N26: good-web-game

### PR DESCRIPTION
**Pull request by PSteinhaus**
_Part of #783_

### CODE REVIEW

**Review by ozkriff — CHANGES_REQUESTED** [review]
I like the PR overall but it's a little bit too long - ~1.5k visible characters while the style guide requires "<...> The rendered text should be under 1000 characters <...>".

Could you please remove some non-essential information?

**Comment by ozkriff** [comment]
Cool logo, btw!

**Comment by PSteinhaus** [comment]
> Cool logo, btw!

Thanks! :D

> Could you please remove some non-essential information?

Will do.

**Comment by PSteinhaus** [comment]
I didn't count the words, but I think it's short enough now, right?
I'm content with it now.

**Review by ozkriff — APPROVED** [review]
:+1:

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
