### PR TITLE
N37: Math It

### PR DESCRIPTION
**Pull request by Vrixyz**
Part of #1134 

There was the [bevy jam 2](https://itch.io/jam/bevy-jam-2) this month, so I figured I would add my entry.

⚠️ We might want to wait until next month to coordinate a few jam entries and the jam recap by @cart which he mentionned he would want to write ?

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
Content looks good, but good point about maybe wanting to coordinate with other jam stuff - I'm not opposed to potentially having it in both newsletters (since the context would be a bit different), but interested to hear @ozkriff / @AngelOnFira 's views before merging :)

**Review by ozkriff — APPROVED** [review]
> I'm not opposed to potentially having it in both newsletters (since the context would be a bit different)

I'm ok with it too

**Comment by Vrixyz** [comment]
Feel free to merge whenever you want :)

**Comment by cart** [comment]
I just put out a Bevy Jam 2 PR following the same format used for Bevy Jam 1: #1151 

Happy to coordinate however is needed, but it looks like these PRs won't need any changes / we can include both.

**Pull request merged**
