### PR TITLE
N15: Power Kick

### PR DESCRIPTION
**Pull request by kakoeimon**
Part of #320 ("Newsletter 15")

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
The content looks good! There's just a few style issues that need fixing to pass the CI check:

```
content/posts/newsletter-015/index.md:67:112 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-015/index.md:67:81 MD013/line-length Line length [Expected: 80; Actual: 112]
content/posts/newsletter-015/index.md:68:81 MD013/line-length Line length [Expected: 80; Actual: 259]
content/posts/newsletter-015/index.md:70:81 MD013/line-length Line length [Expected: 80; Actual: 87]
content/posts/newsletter-015/index.md:72:81 MD013/line-length Line length [Expected: 80; Actual: 165]
content/posts/newsletter-015/index.md:74:81 MD013/line-length Line length [Expected: 80; Actual: 110]
```

**Comment by kakoeimon** [comment]
@17cupsofcoffee Done.

**Review by 17cupsofcoffee — APPROVED** [review]
:+1:

**Review by ozkriff — APPROVED** [review]
:+1:  (made a few small fmt&style tweaks for consistency with the rest of the newsletter)

**Pull request merged**
