### PR TITLE
Rust Graphics Meetup 2 Blog

### PR DESCRIPTION
**Pull request by AngelOnFira**
Hoping to get this out today to advertise for the meetup :)

### CODE REVIEW

**Comment by AngelOnFira** [comment]
@lukors @attackgoat @cwfitzgerald For you to check out :)

**Review by cwfitzgerald — APPROVED** [review]
Good from my end

**Comment by AngelOnFira** [comment]
I'll get this merged once I get an approval from one of the other WG members :)

**Comment by AngelOnFira** [comment]
I'm going to merge now and beg for forgiveness later :sweat_smile: just so that I can get the word out tonight

**Review by 17cupsofcoffee — APPROVED** [review]
LGTM :+1:

**Pull request merged**
