### PR TITLE
N22: The Process

### PR DESCRIPTION
**Pull request by setzer22**
Added my piece on _The Process_

_Part of #640_

### CODE REVIEW

**Comment by setzer22** [comment]
Ok, I think this is ready for review now :+1: 

I believe you can you squash the commits during the merge on your side? Or is there something I need to do myself?

**Review by 17cupsofcoffee — APPROVED** [review]
Looks good to me! We can squash when merging :+1:

I was able to squash the GIF a bit more to shave off ~25% of the size - might be worth swapping it out for this one:

the_process

**Comment by setzer22** [comment]
Thanks!

> I was able to squash the GIF a bit more to shave off ~25% of the size - might be worth swapping it out for this one:

Fine by me! Anything I need to do?

**Comment by AngelOnFira** [comment]
All good :100:

**Pull request merged**
