### PR TITLE
N15: Ajour

### PR DESCRIPTION
**Pull request by casperstorm**
Part of #320 ("Newsletter 15")

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
Content looks good to me.

**Comment by casperstorm** [comment]
> Content looks good to me.

Cool, otherwise let me know and I can easily go into something specific. :)

**Review by ozkriff — APPROVED** [review]
:fire:

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
