### PR TITLE
N17: Veloren

### PR DESCRIPTION
**Pull request by AngelOnFira**
Part of #408 :tada:

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Content looks good, but there's a few formatting issues tripping up the CI build:
```
content/posts/newsletter-017/index.md:112:81 MD013/line-length Line length [Expected: 80; Actual: 99]
content/posts/newsletter-017/index.md:113:81 MD013/line-length Line length [Expected: 80; Actual: 92]
content/posts/newsletter-017/index.md:115:81 MD013/line-length Line length [Expected: 80; Actual: 92]
content/posts/newsletter-017/index.md:122:81 MD013/line-length Line length [Expected: 80; Actual: 85]
content/posts/newsletter-017/index.md:123:81 MD013/line-length Line length [Expected: 80; Actual: 87]
content/posts/newsletter-017/index.md:125:81 MD013/line-length Line length [Expected: 80; Actual: 104]
content/posts/newsletter-017/index.md:127:81 MD013/line-length Line length [Expected: 80; Actual: 82]
content/posts/newsletter-017/index.md:128:81 MD013/line-length Line length [Expected: 80; Actual: 88]
content/posts/newsletter-017/index.md:129:81 MD013/line-length Line length [Expected: 80; Actual: 106]
content/posts/newsletter-017/index.md:130:81 MD013/line-length Line length [Expected: 80; Actual: 85]
content/posts/newsletter-017/index.md:132:81 MD013/line-length Line length [Expected: 80; Actual: 97]
content/posts/newsletter-017/index.md:133:81 MD013/line-length Line length [Expected: 80; Actual: 109]
```

It also looks like you may have accidentally committed some changes to the front matter/intro of the post. For future reference, if you need to preview the post locally, you can run Zola with the `--drafts` flag to avoid having to edit the flag in the post :)

**Comment by AngelOnFira** [comment]
I totally forgot about the drafts :sweat_smile: and good to know the command :ok_hand: I also always forget to turn off my default markdown formatted :stuck_out_tongue: but it should all be good now!

**Review by 17cupsofcoffee — APPROVED** [review]
👍

**Comment by ozkriff** [comment]
> I also always forget to turn off my default markdown formatted

@AngelOnFira you editor doesn't recognize `.markdownlint.json`? What editor/plugin are you using? :thinking:

**Comment by AngelOnFira** [comment]
VS Code / Prettier. I'll take a look at if it's having any trouble reading the markdown lint file.

**Comment by ozkriff** [comment]
Yeah, looks like Prettier doesn't look at `.markdownlint.json`. Well, we might create and commit `.prettierrc.json` that fits newsletter's style too.

**Comment by ozkriff** [comment]
Attempted to rework the section: 

- the original dense list of links to all sections from 100th devlog isn't consistent with how we usually do this (and looks weird on mobile browser), so I've converted it to a list of highlights.
- fixed links
- removed the third image to make the section a little more compact.

@AngelOnFira are you ok with these changes?

**Comment by AngelOnFira** [comment]
@ozkriff Looks good to me! I wasn't sure how to compact it, so I'm glad you found a way. Sorry for all the extra work :sweat_smile:

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Thanks for the PR!!

**Pull request merged**
