### PR TITLE
N44: Boat Journey

### PR DESCRIPTION
**Pull request by gridbugs**
_Part of https://github.com/rust-gamedev/rust-gamedev.github.io/issues/1317_

### CODE REVIEW

**Review by AngelOnFira — APPROVED** [review]
Very neat game! It would be awesome to have you show it off at the next gamedev meetup :smile:

**Comment by gridbugs** [comment]
> Very neat game! It would be awesome to have you show it off at the next gamedev meetup 😄

Thanks :) Yeh I'd be happy to show it off. When is the next meetup?

**Comment by gridbugs** [comment]
Oh I just found https://github.com/rust-gamedev/meetup/issues/6 which answers my question. I'm in Sydney and it looks like it will start at 2am for me which might be tricky.

**Comment by gridbugs** [comment]
Rebased and fixed the conflict

**Comment by AngelOnFira** [comment]
Ah yes, the meetup time is really not accessible for Asia/Oceania timezones 😅 I'll see if I can do something about that and get back to you about it!

**Pull request merged**
