### PR TITLE
N21: Add KindNES

### PR DESCRIPTION
**Pull request by henryksloan**
Part of #589

### CODE REVIEW

**Review by ozkriff — COMMENTED** [review]
lgtm, except that we've historically put similar projects into the "Library & Tooling Updates" section

**Comment by 17cupsofcoffee** [comment]
Whoops, that's my bad, I put it in the game updates section in the original post.

**Review by 17cupsofcoffee — APPROVED** [review]
:+1: LGTM, and I've move the section to where @ozkriff wants it :)

**Review by ozkriff — APPROVED** [review]

**Comment by 17cupsofcoffee** [comment]
Thank you for the PR!

**Pull request merged**
