### PR TITLE
N17: Textyle

### PR DESCRIPTION
**Pull request by AngelOnFira**
For #408 :+1:

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]

**Comment by ozkriff** [comment]
:construction: (adding an image)

**Review by ozkriff — APPROVED** [review]
:+1: (added an image and a discussion link)

**Comment by ozkriff** [comment]
^ @stefandevai jfyi

**Comment by ozkriff** [comment]
Merged, thanks!

**Pull request merged**
