### PR TITLE
N43: Cootsmania

### PR DESCRIPTION
**Pull request by kuviman**
Part of #1287

### CODE REVIEW

**Review by AngelOnFira — CHANGES_REQUESTED** [review]
If we could reduce the `cootsmania.png` image size, then it should be good :) Maybe switch both to jpgs?

**Comment by AngelOnFira** [comment]
@kuviman out of curiosity, might it be interesting to add a section on `geng` as well?

**Comment by kuviman** [comment]
switched both to jpg and rescaled the first one to 50% size

talking about `geng`, im not trying to make other people use it, but if you're interested I can write a small section - there were sound & font related updates in february

**Review by ozkriff — CHANGES_REQUESTED** [review]
I'm afraid that [out style guide](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md#style-guidelines) allows only one image:

> Only include one image (<300kb) or GIF (<2.5mb).
> - Images should be placed before text, with an optional caption and mandatory alternate text for accessibility.
> - Unless essential to demonstrating your project, prefer static images over GIFs, to keep the file size down.

Otherwise LGTM

**Comment by ozkriff** [comment]
> talking about `geng`, im not trying to make other people use it, but if you're interested I can write a small section - there were sound & font related updates in february

@kuviman yeah, we're definitely interested in a PR with geng updates section!

**Review by ozkriff — APPROVED** [review]
:+1: (removed one image and made a couple of style tweaks after the discussion in Telegram )

**Comment by ozkriff** [comment]
Thanks for the PR, Vitaliy!

**Pull request merged**
