### PR TITLE
N24: Release

### PR DESCRIPTION
**Pull request by 17cupsofcoffee**
_Part of #719_

Preview (63f9e3f): https://sharp-aryabhata-9cc78b.netlify.app/news/024/

Aiming to release this in a few hours if there's no objections.

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]
LGTM overall but here're a few nitpicks/suggestions after a quick glance through

- typo: Sproingers -> Springers
- The "Writing an RPG using rg3d" section could use an image like [this](https://rg3d.rs/assets/rpg-tutorial1/scene.jpg) or even a preview image for one of the youtube demo videos
- In the "Fish Fight" the 2nd-level sublist of weapons could be collapsed into one line to save space without much harm. Also, `@fedor_games and @erlend_sh` could be turned into links to the corresponding Twitter acoounts.

**Comment by 17cupsofcoffee** [comment]
I think 'sproingers' might be intentional ('sproing' being onomatopoeia for the noise a spring would make), but I could be wrong - @erlend-sh? :)

Will make the other two changes when I get a sec.

**Comment by gschup** [comment]
Oh no! It seems I forgot to put a direct link to my fancy new website! 

It's no big deal if not possible (website is accessible through my github link), but I would appreciate if you could add a link to: https://gschup.github.io/ggrs/ in the GGRS section. 

Thank you!

**Comment by 17cupsofcoffee** [comment]
Made most of those fixes :+1:

I did try collapsing the Fish Fight list, but I found it less readable personally due to the number of items/nested parentheses. I think keeping the list this time is okay since it directly corresponds to what's in the associated image, but in future we maybe wouldn't want to go into quite so much detail on individual items.

**Comment by 17cupsofcoffee** [comment]
Preview updated: https://sharp-aryabhata-9cc78b.netlify.app/news/024/

**Comment by AngelOnFira** [comment]
The section "writing an RPG using rg3d" doesn't have any links to the mentioned video (other than the title link). Might be nice to add something inline? (@mrDIMAS)

image

**Comment by AngelOnFira** [comment]
Other than my previous comment, everything else looks good :+1:

**Comment by 17cupsofcoffee** [comment]
Linked the video (via the image and the caption) and added an inline link to the tutorial: 
image

Will give it another half an hour for any last minute comments and then publish :)

**Comment by kvark** [comment]
We have identical Zemeroth screenshots in 2 different sections. I think this needs to be fixed.

**Comment by 17cupsofcoffee** [comment]
@kvark: That was because I didn't have a better screenshot for the Macroquad section - if you think it looks weird, I'll get rid of the duplicate :+1:

**Comment by kvark** [comment]
Yeah, I don't think we should have the duplicate here.
Also, minor fix would be nice - in "wgpu-rs's "help wanted" issues" the link is correct, but the text should just say "wgpu's "help wanted" issues" (instead of wgpu-rs), since wgpu-rs repo is archived now

**Review by kvark — APPROVED** [review]
Skimmed through it, all is good outside of the issues noted in the comments

**Review by AngelOnFira — APPROVED** [review]

**Comment by 17cupsofcoffee** [comment]
@kvark: Swapped out the duplicate image for a different one, and fixed the WGPU issue text :+1:

**Pull request merged**
