### PR TITLE
Newsletter 7

### PR DESCRIPTION
**Pull request by ozkriff**
**Netlify preview**: https://rust-gamedev-preview.netlify.com/posts/newsletter-007

This PR:

- adds sections:
  - weasel
  - glium
  - riven
  - RLTK/bracket-lib
  - rustsim 9
  - luminance v0.39
  - miniquad
  - superluminal-perf-rs
  - RG-300
  - Pushrod
  - tikan
  - gfx/wgpu
  - issues
  - bonus: It's Not Cool
- Updates RustTallinn
- Makes lots of style tweaks
- Reorders some sections
- Adds release date and removes the draft flag

------

_Part of #64 ("Newsletter 7: Coordination/Tracking")_

### CODE REVIEW

**Comment by ozkriff** [comment]
Everyone is invited to review!

:timer_clock:  Hope te merge this in a few hours if there're no objections!

**Comment by PsichiX** [comment]
looks good to me

**Comment by AngelOnFira** [comment]
Is it possible to make images that link to videos do so in another tab? I can also make this an issue if it is out of scope.

**Comment by 17cupsofcoffee** [comment]
> Is it possible to make images that link to videos do so in another tab? I can also make this an issue if it is out of scope.

There's three potential ways you could do this (all of which are fairly nasty 😅):

* [Use an `a` tag in the `.md` file so you can set the target attribute.](https://stackoverflow.com/a/4425223)
* Post-process the markdown somehow (would probably require a PR to Zola).
* [Use JavaScript to add target attributes to the links at runtime.](https://stackoverflow.com/a/4425214)

The last option sounds like the most pragmatic (I don't like the idea of cluttering our Markdown files with tons of inline HTML), but it's still a little kludgy.

**Comment by ozkriff** [comment]
@repi Updated Superluminal section!

@AngelOnFira yeah, I guess it's better to open an issue about it.

**Pull request merged**
