### PR TITLE
N15: Arsenal

### PR DESCRIPTION
**Pull request by zicklag**
If the logo is to tall I can create a thinner version of it or something. Up to you. :slightly_smiling_face: 

**Edit:** Nevermind, changed the logo to a thin one.

_Part of #320 ("Newsletter 15")_

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
LGTM

**Review by ozkriff — APPROVED** [review]
:+1: but needs a few style tweaks

**Comment by ozkriff** [comment]
[CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md):
> Make sure that the "Allow edits from maintainers" box is checked (avoid using org accounts if possible) - it makes updating/tweaking the PR easier for the coordinators.

Updated and merged manually in https://github.com/rust-gamedev/rust-gamedev.github.io/commit/17f39732fde7a182bc2673fa32c2d05edf3f3057

Thanks for the PR!

**Comment by zicklag** [comment]
> Make sure that the "Allow edits from maintainers" box is checked (avoid using org accounts if possible) - it makes updating/tweaking the PR easier for the coordinators.

Ah, sorry 'bout that. I thought that was checked by default usually. 

> Thanks for the PR!

Thanks for the newsletter! :slightly_smiling_face:

**Pull request closed without merging**
