### PR TITLE
N34: Release

### PR DESCRIPTION
**Pull request by ozkriff**
Preview (https://github.com/rust-gamedev/rust-gamedev.github.io/commit/e1191f1a17c96ce13ebf123797d236cbc1042a4f): https://rust-gamedev-preview.netlify.app/news/034

Everyone is invited to review!

Hope to merge this in a few hours if there're no objections.

_Part of #1033_

### CODE REVIEW

**Comment by AngelOnFira** [comment]
@ozkriff I have some changes in https://github.com/ozkriff/rust-gamedev.github.io/pull/4

**Comment by AngelOnFira** [comment]
Can we reduce the size of these images?

```
content/news/034/cnc-preview.png
content/news/034/dims-video-preview.jpg
content/news/034/gfs-youtube-preview.jpg
```

**Review by AngelOnFira — APPROVED** [review]
After my recommendations are fixed, it looks good to me :tada:

**Review by 17cupsofcoffee — APPROVED** [review]
LGTM :+1:

**Review by ManevilleF — APPROVED** [review]

**Pull request merged**
