### PR TITLE
Newsletter 8

### PR DESCRIPTION
**Pull request by ozkriff**
Preview (095d893): https://rust-gamedev-preview.netlify.com/posts/newsletter-008

This PR:
- Removes the London Talks section (it will be a part of the next newsletter).
- Optimizes some images.
- Makes lots of small style tweaks.
- Adds release date and removes the draft flag.

Everyone is invited to review!

:timer_clock: Hope to merge this today +- at 15:00 UTC (in six hrs from now) if there no objections.

---

_Part of #89 ("Newsletter 8: Coordination/Tracking")_

### CODE REVIEW

**Comment by PsichiX** [comment]
:+1:

**Comment by ozkriff** [comment]
:watch: Merging in 30m.

**Comment by 17cupsofcoffee** [comment]
🎉 🎉 🎉 Great work again by everyone, thanks for co-ordinating @ozkriff :)

**Comment by ozkriff** [comment]
https://rust-gamedev.github.io/posts/newsletter-008

Many thanks to all contributors and reviewers!

**Pull request merged**
