### PR TITLE
N51: CyberGate Playground

### PR DESCRIPTION
**Pull request by cybersoulK**
Part of #1496

### CODE REVIEW

**Comment by cybersoulK** [comment]
can we have mp4? 

This is something i always hated and takes a lot of time. When i use tools to convert mp4 to .gif, the size triples. 

If i compress to lower quality / low fps, it loses the fluidity that is needed to understand the movements in a 3D game.

**Comment by cybersoulK** [comment]
image
Ohh i am 1500, so lucky

**Comment by janhohenheim** [comment]
Not sure about mp4, I'll need to check. Moving this to next month / N51 :)

**Comment by cybersoulK** [comment]
I am closing since the changes would be late news.
But if you guys think my project is worthy, add my name to the N51

**Comment by janhohenheim** [comment]
@cybersoulK I'd include it like this and just say "in the last couple of months"

**Comment by janhohenheim** [comment]
Moved to https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1517

**Pull request closed without merging**
