### PR TITLE
Newsletter 13: Add NeoCogi's libs

### PR DESCRIPTION
**Pull request by eloraiby**
_Part of #232 ("Newsletter 13")_

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
There's a few formatting issues being flagged by the CI job:

```
content/posts/newsletter-013/index.md:69 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### NeoCogi's libraries"]
content/posts/newsletter-013/index.md:70:81 MD013/line-length Line length [Expected: 80; Actual: 214]
content/posts/newsletter-013/index.md:72 MD045/no-alt-text Images should have alternate text (alt text)
content/posts/newsletter-013/index.md:74:81 MD013/line-length Line length [Expected: 80; Actual: 99]
content/posts/newsletter-013/index.md:75:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-013/index.md:75 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "* The new code should still in..."]
content/posts/newsletter-013/index.md:76:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
content/posts/newsletter-013/index.md:78:81 MD013/line-length Line length [Expected: 80; Actual: 185]
content/posts/newsletter-013/index.md:80:81 MD013/line-length Line length [Expected: 80; Actual: 135]
content/posts/newsletter-013/index.md:86 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

Changes that are needed to make the linter happy are:

* Add an extra line after the heading
* Add alt text for the images (goes inside the `[]` for the image embed syntax)
* Lines should not be longer than 80 characters
* Replace the `*`  with `-` for the list items
* Add a line break above the list
* Remove one of the linebreaks before the next heading

**Review by 17cupsofcoffee — APPROVED** [review]
👍 thanks for fixing!

**Comment by eloraiby** [comment]
Checks have passed, no merge conflicts, @ozkriff please validate!

**Review by ozkriff — APPROVED** [review]
:+1:  (made a few style tweaks for consistency and converted to third-person)

**Comment by ozkriff** [comment]
Merged, thanks for the PR! Good luck with the rest of RIIR! :)

**Comment by eloraiby** [comment]
Thanks!

**Pull request merged**
