### PR TITLE
N36: Rust Game Ports Officialization

### PR DESCRIPTION
**Pull request by 64kramsystem**
N36: Rust Game Ports Officialization.

This would fit better an announcements section, but this month, there isn't any :smile:

### CODE REVIEW

**Comment by 17cupsofcoffee** [comment]
@AngelOnFira is adding an Announcements section for https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1127, so you can still put it there. It'd either go there or Learning Material Updates, I think - Other News is for one-liners.

**Comment by 64kramsystem** [comment]
> @AngelOnFira is adding an Announcements section for #1127, so you can still put it there. It'd either go there or Learning Material Updates, I think - Other News is for one-liners.

Ah, thanks! I think this'd be better suited for announcements, since the project itself was published in the last issue; I'll update this PR once #1127 is in.

**Comment by ozkriff** [comment]
:construction: wip

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Tnx!

**Pull request merged**
