### PR TITLE
Add gfx-rs org news

### PR DESCRIPTION
**Pull request by kvark**
------

Part of #89 (_"Newsletter 8: Coordination/Tracking"_)

### CODE REVIEW

**Comment by ozkriff** [comment]
Also, maybe there's some new image that can be added to the section?

**Comment by kvark** [comment]
@ozkriff fixed now. As for the screenshot, I can only think of https://user-images.githubusercontent.com/2113872/76693508-5866cf80-6649-11ea-9d8b-7624ff84ae05.png

**Comment by ozkriff** [comment]
@kvark well, yeah, it's not the most visually exciting pic. Let's merge the text-only version for now then :)

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
