### PR TITLE
CI: Add markdownlint

### LINKED ISSUE #30: CI: Add markdownlint checks

### PR DESCRIPTION
**Pull request by ozkriff**
Consistency is King

Closes #30 (_"CI: Add markdownlint check"_)

### CODE REVIEW

**Comment by ozkriff** [comment]
Yeah, that's a bit unfortunate. Maybe we'll find a better gh action later, atm I'm more interested in having the linter on CI at all)

**Comment by ozkriff** [comment]
:timer_clock: Merging in a few hrs if there're no objections.

**Comment by ozkriff** [comment]
@kvark Well, the newsletter is written by many people at once, I'm afraid that we'll quickly face conflicts of different ways of writing the same thing. Also, MD isn't standardized enough - it's quite easy to step into differences between render engines (even in basic things like indents, quotes, and linebreaks) if you're not careful.

**Comment by kvark** [comment]
Talked over matrix, let's do it:)

**Pull request merged**
