### PR TITLE
N14: Riddle

### PR DESCRIPTION
**Pull request by vickles**
Related to: #278

### CODE REVIEW

**Review by 17cupsofcoffee — COMMENTED** [review]
Content looks good to me, but I think the preferred style is to link to things like GitHub and docs within the text itself rather than having a link dump at the end. Might be worth making the title and the first word of the section link to the Github and work the docs link into the text?

The one exception to that is discussion threads, which are usually formatted like this at the end of the section:

```markdown
_Discussions: [/r/rust](https://reddit.com/r/rust/todo), [twitter](https://twitter.com/todo/status/123456)_
```

See the template for more context: https://raw.githubusercontent.com/rust-gamedev/rust-gamedev.github.io/source/newsletter-template.md

**Comment by vickles** [comment]
I've removed the link dump and placed them in the body of the post as suggested

**Review by 17cupsofcoffee — APPROVED** [review]
That's perfect, thank you!

**Comment by ozkriff** [comment]
Awesome, thanks!

**Pull request merged**
