### PR TITLE
Added Oxygengine section to newsletter 10th issue

### PR DESCRIPTION
**Pull request by PsichiX**
_Part of #139 ("Newsletter 10: Coordination/Tracking")_

### CODE REVIEW

**Comment by PsichiX** [comment]
sure! give me a sec :)

**Comment by ozkriff** [comment]
Also, cropped the TTF image a bit.

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Comment by PsichiX** [comment]
thanks! :D

**Pull request merged**
