### PR TITLE
N49: CyberGate

### PR DESCRIPTION
**Pull request by cybersoulK**
Part of #1440

### CODE REVIEW

**Review by AngelOnFira — APPROVED** [review]
LGTM 🥇

**Review by ozkriff — APPROVED** [review]
:+1: (made a few style tweaks for consistency with the rest of the newsletter)

**Comment by ozkriff** [comment]
Thanks for the PR - and sorry for the late review!

**Comment by cybersoulK** [comment]
Wow thank you for editing ozkriff, looks great

**Pull request merged**
