### PR TITLE
Newsletter 9: Add ABstreet, Citybound and Scale updates

### PR DESCRIPTION
**Pull request by Uriopass**
Part of #111

### CODE REVIEW

**Comment by ozkriff** [comment]
Tweaked formatting and wording a bit to make the PR more consistent with the rest of the newsletter.

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Comment by ozkriff** [comment]
@aeplay fyi ^

**Comment by aeplay** [comment]
Thanks for the feature! @ozkriff @Uriopass

**Pull request merged**
