### PR TITLE
Adds paragraph about Edict 0.2

### PR DESCRIPTION
**Pull request by zakarumych**
_Part of #1134_

Adds paragraph about upcoming update Edict 0.2

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Sorry for the delay in reviewing, think everyone has been a bit busy this month.

This section seems a bit long/overly technical to me - we generally try to keep them below 1000 rendered characters, give or take. I appreciate some level of detail is needed to get across what makes Edict different from the (many 😅) other Rust ECS libraries, but if possible it'd be good to make this a bit closer in length to the other sections.

**Comment by zakarumych** [comment]
Not many enough I guess, since new ones are popped like sprouts in the spring.

**Comment by AngelOnFira** [comment]
Does this edit look ok? I'm trying to improve the section for clarity.

image

**Comment by zakarumych** [comment]
Looks good to me

**Review by AngelOnFira — APPROVED** [review]

**Pull request merged**
