### PR TITLE
N32: Way of Rhea

### PR DESCRIPTION
**Pull request by MasonRemaley**
Let me know if anything needs to be tweaked! :)

_Part of #979_

### CODE REVIEW

**Comment by AngelOnFira** [comment]
1000 🥳 :tada:

**Comment by AngelOnFira** [comment]
Are you able to reduce the size of the image? Preferably jpeg too if possible :)

**Review by AngelOnFira — CHANGES_REQUESTED** [review]
Just the image size reduced, and it should be good :)

**Comment by MasonRemaley** [comment]
Whoops, I uploaded the full resolution image by accident--fixed & converted to jpg!

**Review by 17cupsofcoffee — APPROVED** [review]

**Pull request merged**
