### PR TITLE
Add everpuzzle to newsletter 7

### PR DESCRIPTION
**Pull request by Skytrias**
Tried to keep it smaller

-----

_Part of #64 ("Newsletter 7: Coordination/Tracking")_

### CODE REVIEW

**Comment by AlexEne** [comment]
Thanks for this, I approved it but I think the sentence needs some tweaking:
> Back then the project was using Amethyst with ECS, which wasn't nice to write game logic in.

**Comment by Skytrias** [comment]
> 
> 
> Thanks for this, I approved it but I think the sentence needs some tweaking:
> 
> > Back then the project was using Amethyst with ECS, which wasn't nice to write game logic in.

sure, i somehow have to explain the move away from amethyst in the nicest way, any suggestion?
it was mainly because of compile times, game logic not translating too well in ECS systems, quirks like gamepad support etc.

**Comment by AngelOnFira** [comment]
@Skytrias I think it's important to be critical of Amethyst if you have reason to be. You used it, and have knowledge of ways it didn't work. However, saying it bluntly doesn't really fit the newsletter I think. It would do better as a part of a devblog post instead. Maybe it could say this instead?
```
Everpuzzle aims to become a similar game like Tetris Attack and expand on its concepts. The project was recently rewritten with minimal dependencies to achieve small compile times and gain more control over the underlying engine architecture. In the past Everpuzzle was using Amethyst with ECS, however there were some issues that made development difficult.
```

**Comment by AlexEne** [comment]
Saying that you changed from amethyst to your own ECS system is probably fine. E.g. 
> Switched from Amethyst to my own entity management system that allows me to...

**Comment by Skytrias** [comment]
> Saying that you changed from amethyst to your own ECS system is probably fine. E.g.
> 
> > Switched from Amethyst to my own entity management system that allows me to...

thing is im just using plain enums now instead of ecs, so is that really my own entity management?

**Comment by Skytrias** [comment]
> > Everpuzzle aims to become a similar game like Tetris Attack and expand on its concepts. The project was recently rewritten with minimal dependencies to achieve small compile times and gain more control over the underlying engine architecture. In the past Everpuzzle was using Amethyst with ECS, however there were some issues that made development difficult.

that sounds better!

**Comment by ozkriff** [comment]
Fixed a few markdown issues and resolved merge conflicts.

**Comment by ozkriff** [comment]
:timer_clock: Merging in a few hours if there're no objections.

**Comment by ozkriff** [comment]
Merged! Thanks for the PR!

**Pull request merged**
