### PR TITLE
Release N52

### LINKED ISSUE #1523: Newsletter 52: June 2024
**Editors:** @janhohenheim, @AngelOnFira, @mamaicode

Another month has gone by, so it's time to put together the Rust Gamedev newsletter with June's news!

## Current Schedule

The deadline for all section PRs is the **28th of June, 2024**. Submissions after this date will be added to the next newsletter.
Our target release date is the **3rd of July, 2024**.

## Current Structure & Status

Below is our current planned structure for the newsletter, and the status of each PR (which we'll try to keep updated).

This is **not** an exhaustive list - if you have your own project that you want to write about, just make a comment on this issue and open a PR!

### Game Updates

- [x] https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1529
- [x] https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1531

### Learning Material Updates

None yet. Feel free to submit yours!

### Engine Updates

- [x] Bevy 0.14 RC by @alice-i-cecile? @janhohenheim can do this as well
- [x] https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1532

### Tooling Updates

- [x] https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1528

### Library Updates

- [x] egui_ratatui: https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1526

### Other News

- [x] [Tiny Glade Developers Discuss Bevy, Proceduralism, Publishers & Cozy Games](https://80.lv/articles/exclusive-tiny-glade-developers-discuss-bevy-proceduralism-publishers-cozy-games/) by @anopara and @h3r2tic
- [x] [Larian cinematics: A Top-Down look at our Bottom-Up approach in 'baldur's gate 3'](https://www.youtube.com/watch?v=MdmY9Mt-vz8)
- [x] https://github.com/rust-gamedev/rust-gamedev.github.io/pull/1530

### Discussions

- [x] https://dioxus.notion.site/Dioxus-Labs-High-level-Rust-5fe1f1c9c8334815ad488410d948f05e

### Social Media

- [x] Reddit
- [x] Lemmy
- [x] Mastodon
- [x] Twitter/X
- [x] Hacker News

### Discord Servers

- [x] Rust GameDev
- [x] Bevy
- [x] Blue Engine
- [x] Macroquad
- [x] Fyrox
- [x] LogLogGames (comfy engine)
- [x] Spicy Lobster
- [x] Rust Godot

Let us know if you also want to receive monthly reminders on your Discord server!

## Publishing Steps

- [x] Final review - by everyone
- [ ] Publish - by @janhohenheim
- [ ] Post together with next calls for submissions - by @janhohenheim
- [ ] Pin thread on social media - by @janhohenheim
- [ ] Add comment links - by @janhohenheim

## How to Contribute

If you want to help writing the newsletter:

- **Read [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md?rgh-link-date=2023-09-12T16%3A17%3A34Z).**
- Choose one or more of the "🆓 **free**" sections listed below, and leave a comment letting us know you want to work on them.
  - The links in brackets (like `[1](#), [2](#), [3](#)`) are suggestions of links to include in the section. Feel free to add more!
  - The username listed next to the section (like `@janhohenheim?`) is a suggestion of who may want to pick up the work (usually the project's developer, or someone who has expressed interest in the past).
  - You are not obligated to write a section if you're tagged or your project is listed! You're welcome to ask someone else to write the section, or to ask for your project to be excluded from this month's post.
  - Extra sections not listed in the plan are welcomed - just leave a comment and open a PR!
- Write a short overview in the newsletter's Markdown file, making sure to follow the style guidelines (see below).
- Send a PR [_to the `source` branch_](https://github.com/rust-gamedev/rust-gamedev.github.io/tree/source) (example PR: [N15: A/B Street #336](https://github.com/rust-gamedev/rust-gamedev.github.io/pull/336)).
- Mention this issue in your PR's description to link it all together.

## Style Guidelines

The full style guide is in [CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md?rgh-link-date=2023-09-12T16%3A17%3A34Z),
but here are the most important rules:

- Write in third-person perspective.
- Each line must be 160 characters or less, for ease of reviewing/diffing.
- Only one image per section is allowed.
  - The maximum size is 300kb for static images and 2.5mb for GIFs.
  - The image should come before the text, and must have alt text for accessibility.
  - Prefer static images to GIFs, to keep the page load times down.
- Each section should be under 1000 characters, and under 6 paragraphs.
  - This only applies to the rendered text, not the markup.
- Keep formatting minimal - no bold/italics/etc.
- Avoid long/nested bullet point lists - no changelogs!

Please use these templates as a starting point:

**Games/apps/libraries:**

```md
### [Game name]

![alt text](img)
_optional image label_

[Game name] ([GitHub], [Discord], [Twitter]) by [@nickname]
is... {short project description in one sentence}.

{An overview of the recent updates with links to more details}.

_Discussions: [/r/rust_gamedev](link), [Twitter](link), [etc](link)_

[Game name]: http://example.com
```

**Articles/blog posts/videos/etc:**

```md
### [Article name]

![alt text](img)
_optional image label_

[@nickname] published an [article] about...
{overview what the resource is about}.

_Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

[Article name]: http://example.com
```

### PR DESCRIPTION
**Pull request by janhohenheim**
[Rendered](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/release-52/content/news/052/index.md)

Closes #1523 

Please do not merge before 03.07.2024
If everything goes right, this post will be delivered to a handful of early subscribers per email!

### CODE REVIEW

**Review by Vrixyz — APPROVED** [review]

**Review by AngelOnFira — CHANGES_REQUESTED** [review]
I don't have time to resolve it in my spelling/grammar/formatting pass, but the video for Haalka isn't getting rendered very nicely.

image

**Review by AngelOnFira — CHANGES_REQUESTED** [review]
I think the playdate section needs a formatting pass, since it's quite long, and lots of the formatting on it makes it harder to read. I might put something in my PR, but I also might not figure it out fully.

image

**Comment by AngelOnFira** [comment]
Are the links here Rust-related, or just good GDC talks? I'm not sure it's the best to add completely unrelated content.

image

**Comment by janhohenheim** [comment]
@AngelOnFira the GDCs are not Rust related, but imo it feels like a bit of an omission to not include them in an industry periodical, given how influential GDC is in the game dev space. I could change the header to make it more clear that they are not Rust related if you want

**Comment by janhohenheim** [comment]
Fixed the video width: 
image

**Review by AngelOnFira — APPROVED** [review]

**Review by mamaicode — APPROVED** [review]

**Pull request merged**
