### PR TITLE
N27: Release

### PR DESCRIPTION
**Pull request by 17cupsofcoffee**
_Part of #818_

Netlify preview (a6d3c5f): https://sharp-aryabhata-9cc78b.netlify.app/news/027

### CODE REVIEW

**Comment by danslocombe** [comment]
FYI the youtube link to the recording of the Rust Gamedev meetup leads to a private video
(https://youtu.be/ta2HY4lD3iM)

**Comment by AngelOnFira** [comment]
> FYI the youtube link to the recording of the Rust Gamedev meetup leads to a private video (https://youtu.be/ta2HY4lD3iM)

True, let me go fix that

**Review by ozkriff — APPROVED** [review]
don't have enough time today, so only skimmed through the draft - lgtm overall

**Comment by 17cupsofcoffee** [comment]
:+1: Merging in ~1 hour if no objections.

**Pull request merged**
