### PR TITLE
N16: Learn Wgpu

### PR DESCRIPTION
**Pull request by sotrh**
I didn't really have an image I wanted to use as all the changes have been mostly code based.

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Content looks good :+1: Just needs breaking onto multiple lines to satisfy the CI linter (max length is 80 chars)

**Comment by sotrh** [comment]
I'll get that fixed. For future reference, is there a way to run the CI locally?

**Review by 17cupsofcoffee — APPROVED** [review]
Thank you!

> For future reference, is there a way to run the CI locally?

The CI job runs [markdownlint](https://github.com/DavidAnson/markdownlint). The easiest way to run it locally is to install an editor plugin - there's some links in the [contributor's guide](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md#formatting). I believe your editor should then pick up the [config file](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/.markdownlint.json).

**Review by ozkriff — APPROVED** [review]
:+1:  (made a few small fmt tweaks for consistency wit the rest of the newsletter)

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
