### PR TITLE
Draft of the first newsletter

### PR DESCRIPTION
**Pull request by ozkriff**
This PR adds a draft of the first newsletter (based on initial @aclysma's template).

The idea behind the newsletter's structure is that most of the readers won't really click through most of the links, but because of summaries, they will still get the general picture and a sense in what direction the ecosystem is moving.

[Rendered](https://github.com/ozkriff/rust-gamedev.github.io/blob/newsletter_001/_drafts/newsletter-001.md) (but also check the raw markdown to see the comments).

Related to https://github.com/rust-gamedev/rust-gamedev.github.io/issues/2 (_"Newsletter"_)

### CODE REVIEW

**Comment by 17cupsofcoffee** [comment]
This is excellent :pray:

The focus on having lots of pictures and showing off *actual games* (instead of solely doing ecosystem updates) is something I really hope we can maintain going forward. I think there's a bit of a (not entirely unwarranted) perception that most of the work going on in Rust gamedev is low-level engine-y stuff, and I think the newsletter could really help change that.

I also think having the comments is a great idea - will make this really easy to re-use as a template going forward 😄 

Only potential thing I can think of adding is maybe a link to info on the next meeting in the minutes section.

**Comment by 17cupsofcoffee** [comment]
A few issues were raised about the site's CSS that affected the newsletter template (see #11) - I've just raised PR #14 to resolve those. Might be worth getting those merged before the newsletter goes live!

**Comment by ozkriff** [comment]
> Only potential thing I can think of adding is maybe a link to info on the next meeting in the minutes section.

Done: added a link to the "Join the Fun" section of the WG repo.

> Can we merge/distribute <...> this now?
> I'd agree we should get something out

It should be merged into master, but it shouldn't be distributed yet.

It's only a draft. I deliberately placed into `_drafts` directory [so it don't appear on the rendered blog for now](https://jekyllrb.com/docs/posts/#drafts).

My idea is:

- This PR with a draft of the post is reviewed (seems to be already done) and merged into master.
- Other contributors send PRs with other August news, meeting notes improvements, etc.
- On the first working day of the next month (2019.09.02 in this case) the final PR (that renames the file to `_posts/2019-09-02-newsletter-001.md`) is sent.
- The link to the newsletter is shared on social networks, etc.
- A small PR that adds links to Reddit, Twitter, etc discussions (see the comment at the bottom of the draft) is made.
- PR with a template (a stripped-down version of the first newsletter) is made and the formation of the September newsletter begins.

> Let's call it the September issue <...>

Why? I've called it "This Month in Rust GameDev \#1 - August 2019" because it describes what happened during August.

Isn't that how newsletters are named usually? https://amethyst.rs/posts/activity-report-july-2019 by @erlend-sh, for example, is called "Activity Report - July 2019" and tells about July's events but is released at the beginning of the next month.

> Also, there's still a few TODOs in the newsletter that'll need removing/filling in before this gets merged.

I was going to add a few more news until the end of the month, but I was also hoping that someone (who visits meeting calls regularly?) will help with the content of the "Meeting Minutes" section.

**Comment by Lokathor** [comment]
I suppose, in publishing "the Tuesday paper" is the newspaper that was released Tuesday morning, not that's released after Tuesday describing Tuesday.

**Comment by 17cupsofcoffee** [comment]
Fixes for the dodgy CSS have merged now 👍

**Comment by ozkriff** [comment]
([another monthly newsletter naming precedent from TiKV](https://tikv.org/blog/monthly-july-19/))

@Lokathor Hmm, calling it a September newsletter still feels a little bit wrong to me, but I'm not a native speaker, so I've I created a small poll in Discourse `wg-gamedev` channel and will change the naming scheme if an alternative will be chosen:
image

^ Btw, the third option is to not mention a month in the title at all (like embedded, CLI, and some other WGs do), but it has its own cons.

**Comment by ozkriff** [comment]
Poll results so far are
image
and this question doesn't look like a PR blocker to me (because it's a draft and can be renamed before publishing), which is why I propose merging this PR (so other people can send PRs with content) and creating a separate issue about the title.

So, if there's no objection, I'll merge this PR today somewhere around 16:00 UTC, ok?

**Comment by AlexEne** [comment]
It's ok with me

**Pull request merged**
