### PR TITLE
N46: Fish Folk

### PR DESCRIPTION
**Pull request by erlend-sh**
_Part of #1378_

### CODE REVIEW

**Comment by ozkriff** [comment]
:exploding_head: something went wrong in gh's ui
image

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
I've rewritten the section and added more info and links.

Hope you're ok with my tweaks - feel free to ping me here if you think that something needs to be changed. :)

**Comment by erlend-sh** [comment]
LGTM, thanks you kindly for fixing it up 🙏

**Comment by ozkriff** [comment]
@erlend-sh do you mind if I delete the https://github.com/rust-gamedev/rust-gamedev.github.io-1 repo? both github and vscode's github integration seem to be greatly confused by a pull request from it

**Comment by erlend-sh** [comment]
Go ahead.

**Pull request merged**
