### PR TITLE
CyberGate 7.2

### PR DESCRIPTION
**Pull request by cybersoulK**
part of #1355

### CODE REVIEW

**Comment by ozkriff** [comment]
Content looks good, let me quickly fix the formatting though :construction:

**Review by ozkriff — APPROVED** [review]
(fixed MD formatting and rephrased a couple of things)

**Comment by ozkriff** [comment]
@cybersoulK are you ok with my changes?

**Comment by cybersoulK** [comment]
looks good to me! thank you very much!

**Comment by ozkriff** [comment]
tnx for the pr!

**Pull request merged**
