### PR TITLE
N41: Pirate Annihilation

### PR DESCRIPTION
**Pull request by theredfish**
_Part of #1233 _

### CODE REVIEW

**Comment by theredfish** [comment]
Unfortunately PRs from organizations do not allow edit by maintainers. Let me know if I should reopen it with my personal account.

**Comment by 17cupsofcoffee** [comment]
@theredfish I think that would be a good idea, so that we can rebase/edit :)

**Comment by theredfish** [comment]
Ok will do in a couple of hours ✌️

**Comment by theredfish** [comment]
Closed in favor of #1248 with the possibility to allow maintainers to edit.

**Pull request closed without merging**
