### PR TITLE
N18: Exploring WebSocket with Rust and Tide

### PR DESCRIPTION
**Pull request by pepoviola**
Add a little description about the post and link to game.
Thx!

_Part of #455_

### CODE REVIEW

**Comment by ozkriff** [comment]
It'd be cool to add some image from the article. Like this one

image

otherwise it LGTM :)

**Comment by pepoviola** [comment]
Hi @ozkriff, thanks for the feedback. I will add that image 👍 .

**Review by ozkriff — APPROVED** [review]
:fire:

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
