### PR TITLE
N19: Add Harvest Hero

### PR DESCRIPTION
**Pull request by Bombfuse**
_Part of #496_

### CODE REVIEW

**Review by ozkriff — CHANGES_REQUESTED** [review]
lgtm except for unfixed linter warnings:

content/posts/newsletter-019/index.md:85 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
content/posts/newsletter-019/index.md:90:81 MD013/line-length Line length [Expected: 80; Actual: 100]
content/posts/newsletter-019/index.md:91:81 MD013/line-length Line length [Expected: 80; Actual: 96]

and the GIF's size: 20.5MBs (should be <2.5MB)

**Comment by 17cupsofcoffee** [comment]
Here's the GIF shrinker we usually use, if you need it: https://ezgif.com/optimize

**Comment by 17cupsofcoffee** [comment]
Are you able to make the requested changes @Bombfuse?

**Comment by Bombfuse** [comment]
Apologies, have been very busy this week. Will work on this and try to get it fixed by 10pm PST

**Comment by 17cupsofcoffee** [comment]
No problem, know the feeling :)

**Comment by Bombfuse** [comment]
Amended the commit with an optimized gif and lint updates. Unable to lint locally right now, so I'm using the github PR checks 😅

**Review by 17cupsofcoffee — APPROVED** [review]

**Review by ozkriff — APPROVED** [review]
:+1:

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
