### PR TITLE
N18: teki

### PR DESCRIPTION
**Pull request by o2sh**
Part of  #455

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]
🚀

**Comment by ozkriff** [comment]
Awesome, thanks for the PR. And good luck with the project! :)

**Comment by o2sh** [comment]
The title's hyperlink was broken in my PR --> fixed in 66bb3f2. 
Very sorry about that :disappointed:

**Comment by 17cupsofcoffee** [comment]
@o2sh Thank you for letting us know! I've made a PR to integrate that fix: #460

**Pull request merged**
