### PR TITLE
N16: Survey reminder

### PR DESCRIPTION
**Pull request by erlend-sh**
Part of #365.

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
Looks good, assuming the newsletter goes out in time :)

**Comment by 17cupsofcoffee** [comment]
Ah, actually, this is failing the CI - the text needs to be broken onto multiple lines to satisfy the linter, max length 80 chars.

**Comment by ozkriff** [comment]
:construction: wip

**Review by ozkriff — APPROVED** [review]
:thumbsup: (made a few fmt tweaks for consistency)

**Comment by ozkriff** [comment]
Thanks!

**Pull request merged**
