### PR TITLE
N17: macroquad

### PR DESCRIPTION
**Pull request by not-fl3**

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Content looks good, but there's a few formatting things tripping up the CI build:

```
content/posts/newsletter-017/index.md:115:103 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-017/index.md:115:81 MD013/line-length Line length [Expected: 80; Actual: 103]
content/posts/newsletter-017/index.md:117:267 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
content/posts/newsletter-017/index.md:117:81 MD013/line-length Line length [Expected: 80; Actual: 267]
content/posts/newsletter-017/index.md:119:209 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 3]
content/posts/newsletter-017/index.md:119:81 MD013/line-length Line length [Expected: 80; Actual: 211]
```

You're also missing the URL for your `miniquad` link, by the looks of it.

**Review by 17cupsofcoffee — APPROVED** [review]
:+1: Looks good!

**Review by ozkriff — APPROVED** [review]
:+1:  (made a few style & fmt tweaks)

**Comment by ozkriff** [comment]
Merged, thanks!

**Pull request merged**
