### PR TITLE
N17: Swoop

### PR DESCRIPTION
**Pull request by sdfgeoff**
No idea if the content lines up with what is desired for the newsletter. Feedback welcome

### CODE REVIEW

**Comment by sdfgeoff** [comment]
Part of #408

**Comment by ozkriff** [comment]
:construction:

**Review by ozkriff — APPROVED** [review]
:+1: (Converted to 1st person, split into two sections, and made various style tweaks for the consistency with the rest of the newsletter)

**Comment by ozkriff** [comment]
Merged!

Sorry for butchering your thoughts while editing. The newsletter is more about short overviews for links, not for longer text froms. I tried to keep some of it as quotes though.

**Pull request merged**
