### PR TITLE
Future news section

### PR DESCRIPTION
**Pull request by Vrixyz**
_Part of #1417_

To follow idea from https://github.com/rust-gamedev/rust-gamedev.github.io/issues/1417#issuecomment-1824008515

Not fully tested yet, the ci scripts (date, sed...) are very linux centric so my mac can't run them as-is (I might look into https://github.com/nektos/act, but I'd prefer a granular action to try only parts of those scripts, I wouldn't want to create a commit, issue, etc.

### CODE REVIEW

**Comment by janhohenheim** [comment]
Woah, that's a really good idea, thanks! Let me know when you're done so I can review it :)

**Comment by Vrixyz** [comment]
I considered linking to github.dev (the direct editor from within the browser), but I decided against because it makes it less likely that newcomers read the contribution guidelines.

So I kept the links closer to the original content.

In the long run there could be a script running to add how many pull requests we had etc but I won't go that far yet.

**Comment by janhohenheim** [comment]
@Vrixyz any updates on this? Should I review and maybe merge it?

**Comment by Vrixyz** [comment]
@janhohenheim please do so. I realized there was a call to action at the beginning of the post already linking to pull requests ; so that made me doubt the pertinence to add another one.

Also, Testing "act" locally proved a bit more convoluted than I thought so I didn't test it fully 😕

**Comment by janhohenheim** [comment]
I fixed the script and took the liberty to rewrite some minor phrasing. Merging now. Thanks for adding the section; really good idea :)

**Review by janhohenheim — APPROVED** [review]

**Pull request merged**
