### PR TITLE
N15: Sun Prison

### PR DESCRIPTION
**Pull request by ropewalker**
Part of #320 ("Newsletter 15").

### CODE REVIEW

**Review by 17cupsofcoffee — COMMENTED** [review]
Looks good for the most part! [Your `2` link isn't rendering properly](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/72dc95394b53caad24d21fea27a97ca2abce5320/content/posts/newsletter-015/index.md#sun-prison), though - you can't break the link text and the link ref across 2 lines like that, I don't think.

**Comment by ropewalker** [comment]
@17cupsofcoffee You are right, let me fix it!

**Comment by ropewalker** [comment]
@17cupsofcoffee Fixed now.

**Review by 17cupsofcoffee — APPROVED** [review]
🚀

**Review by ozkriff — APPROVED** [review]
:+1:  (made a few style tweaks)

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
