### PR TITLE
N23: Dango and CrystalOrb

### PR DESCRIPTION
**Pull request by ErnWong**
_Part of #677_

@james7132 and @gschup would it be alright if I compared CrystalOrb to backroll-rs and GGRS in the way it is currently written in the CrystalOrb section?

### CODE REVIEW

**Comment by gschup** [comment]
> _Part of #677_
> 
> @james7132 and @gschup would it be alright if I compared CrystalOrb to backroll-rs and GGRS in the way it is currently written in the CrystalOrb section?

I would be glad if you clarified that while you are sending authorized snapshots of the game (already in the text), backroll-rs and GGRS are only sending input data (currently missing). Thanks :)

**Comment by ErnWong** [comment]
> I would be glad if you clarified that while you are sending authorized snapshots of the game (already in the text), backroll-rs and GGRS are only sending input data (currently missing). Thanks :)

Done, thanks for pointing it out.
I'd be happy to make any further amendments.

**Review by 17cupsofcoffee — APPROVED** [review]

**Review by ozkriff — APPROVED** [review]
:+1:

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
