### PR TITLE
N14: Updates to space_shooter_rs game

### PR DESCRIPTION
**Pull request by tigleym**
Part of #278 (Newsletter 14)

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
Looks good :+1:

**Review by ozkriff — CHANGES_REQUESTED** [review]
lgtm except for the GIF size - we're usually trying to keep gifs under 2 or 3 MBs. 13MB is certainly too big - could you trim it down, please?

**Comment by tigleym** [comment]
> 13MB is certainly too big - could you trim it down, please?

 Sure thing! 👍

**Review by ozkriff — APPROVED** [review]
:space_invader:

**Comment by ozkriff** [comment]
Thanks for the PR!

**Pull request merged**
