### PR TITLE
N17: add doukutsu-rs

### PR DESCRIPTION
**Pull request by alula**
related to #408

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]

**Comment by alula** [comment]
fixed

**Comment by alula** [comment]
@ozkriff

**Comment by ozkriff** [comment]
@alula will review, resolve conflicts, and merge in a few hours.
sorry that it takes so long, I have a hard time with this newsletter issue for various personal reasons :snail:

**Review by ozkriff — APPROVED** [review]
:rocket: (made a few style & fmt tweaks, converted to 3rd person)

**Comment by ozkriff** [comment]
Thanks!

**Pull request merged**
