### PR TITLE
N16: Shotcaller

### PR DESCRIPTION
**Pull request by erlend-sh**
Part of #365.

### CODE REVIEW

**Review by 17cupsofcoffee — CHANGES_REQUESTED** [review]
Content looks good, just some formatting issue tripping up the linter:

```
content/posts/newsletter-016/index.md:66 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
content/posts/newsletter-016/index.md:67 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 3]
content/posts/newsletter-016/index.md:85 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

**Comment by ozkriff** [comment]
:construction:  wip

**Review by ozkriff — APPROVED** [review]
As Shotcaller was already fetured in previous newsletter isues, I've converted this section to only highlight 0.3.1 updates.

**Comment by ozkriff** [comment]
@erlend-sh do you mind the changes?

**Comment by erlend-sh** [comment]
Changes look fine, thanks!

**Review by 17cupsofcoffee — APPROVED** [review]

**Comment by ozkriff** [comment]
Merged, thanks for the PR!

**Pull request merged**
